defaults: &defaults

  shirasete_api:
    open_issues: http://beta.shirasete.jp/projects/<%= "#{ENV['SHIRASETE_PROJECT_ID']}" %>/issues.json?status_id=open&key=<%= "#{ENV['SHIRASETE_API_KEY']}" %>
    issue_categories: http://beta.shirasete.jp/projects/<%= "#{ENV['SHIRASETE_PROJECT_ID']}" %>/issue_categories.json?key=<%= "#{ENV['SHIRASETE_API_KEY']}" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
